### ISSUE TITLE
npm run build fails, when requiring nanologger

### ISSUE THREAD

**Issue by jigargosar** [choojs/create-choo-app#63]
```
npx create-choo-app choo-fail
cd choo-fail
npm add -E nanologger
```
add `require('nanologger')` to  [index.js](https://github.com/jigargosar/choo-fail/blob/master/index.js)

`npm run build` fails with 

```
> choo-fail@1.0.0 build /Users/jigargosar/dev/choo-fail
> bankai build index.js

15:40:35 ✨ Compiling & compressing files

15:40:35 ✨ created: dist
15:40:35 ✨ created: dist/manifest.json
15:40:35 ✨ created: dist/manifest.json.gz
15:40:35 ✨ created: dist/manifest.json.deflate
15:40:35 ✨ created: dist/manifest.json.br
15:40:39 🚨 scripts:browserify.bundle Unexpected token  in JSON at position 199548
SyntaxError: Unexpected token  in JSON at position 199548
    at JSON.parse (<anonymous>)
    at Object.minify (eval at <anonymous> (/Users/jigargosar/dev/choo-fail/node_modules/terser/tools/node.js:21:1), <anonymous>:15755:54)
    at /Users/jigargosar/dev/choo-fail/node_modules/minify-stream/index.js:24:27
    at ConcatStream.<anonymous> (/Users/jigargosar/dev/choo-fail/node_modules/concat-stream/index.js:37:43)
    at emitNone (events.js:111:20)
    at ConcatStream.emit (events.js:208:7)
    at finishMaybe (/Users/jigargosar/dev/choo-fail/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at endWritable (/Users/jigargosar/dev/choo-fail/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at ConcatStream.Writable.end (/Users/jigargosar/dev/choo-fail/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at end (/Users/jigargosar/dev/choo-fail/node_modules/duplexify/index.js:29:36)
```
although `npm run start` works fine :(

Same happened for `require('babel-polyfill')`

[Sample Project](https://github.com/jigargosar/choo-fail)

**Comment by jigargosar** [comment]
```
> npm --version 
6.1.0
> node --version
v8.9.4
```

**Comment by jigargosar** [comment]
Build failing on [travis](https://travis-ci.org/jigargosar/choo-fail/builds/384333656) too :(

**Comment by goto-bus-stop** [comment]
This was fixed in https://github.com/fabiosantoscode/terser/pull/44 but we're still waiting for a new release of that module.

To work around this you can do:

```bash
npm install --save-dev --save-exact minify-stream@1.1.0
```

This will make npm use an older version of minify-stream that uses uglify-es instead of terser.

**Comment by goto-bus-stop** [comment]
A `terser` version including that fix was released some time ago, so this should now work :) Thanks!
