### ISSUE TITLE
SSL key too small, project doesn't start

### ISSUE THREAD

**Issue by Jake-Gillberg** [choojs/create-choo-app#70]
`npm start` fails with below:

```
A critical error occured, forcing Bankai to abort:
Error: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small
at Object.createSecureContext (_tls_common.js:135:17)
at new Server (_tls_wrap.js:873:27)
at new Http2SecureServer (internal/http2/core.js:2839:5)
at createSecureServer (internal/http2/core.js:2963:10)
at /home/dev/baby-math/node_modules/bankai/lib/http-server.js:61:29
at process._tickCallback (internal/process/next_tick.js:68:7)
```

Workaround:
Changing a line in `/etc/ssl/openssl.cnf`
from:
`CipherString = DEFAULT@SECLEVEL=2`
to
`CipherString = DEFAULT@SECLEVEL=1`

but it is probably better to just create a longer ssl key.

Versions:
npm 6.11.3
node v10.16.3
debian buster
openSSL 1.0.2g 1 Mar 2016

**Comment by blahah** [comment]
It's definitely sub-optimal to be failing because the key is too weak. Any secured linux distro will enforce the SSL `DEFAULT@SECLEVEL=2`, and compromising the security of the whole system for the sake of one module seems problematic.

This appears to be a NodeJS core TLS module issue?
